// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORMShowdown;

#nullable disable

namespace ORMShowdown.Migrations
{
    [DbContext(typeof(EFCoreDbContext))]
    [Migration("20230627203036_ExpandedProductData")]
    partial class ExpandedProductData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ORMShowdown.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("Code")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 643,
                            Code = new Guid("2f583545-c72a-4715-b903-6525a5b222d8"),
                            Name = "VOGZSZFQGNWRKWJ",
                            Price = 9965
                        },
                        new
                        {
                            Id = 2,
                            Amount = 868,
                            Code = new Guid("e82c0b6e-f4d0-4b0c-b0c7-b48bc06ca9f3"),
                            Name = "GTRYGYKNRBHXKKV",
                            Price = 5027
                        },
                        new
                        {
                            Id = 3,
                            Amount = 155,
                            Code = new Guid("eb5c0551-91a1-474b-ab5b-f1ef6e77f968"),
                            Name = "UBEKDCQGVDTFIKP",
                            Price = 1002
                        },
                        new
                        {
                            Id = 4,
                            Amount = 228,
                            Code = new Guid("b3c5f882-a37e-4d06-9b6b-690f9dd36c84"),
                            Name = "RAKYNSSIULMQTHJ",
                            Price = 8870
                        },
                        new
                        {
                            Id = 5,
                            Amount = 444,
                            Code = new Guid("513963a2-69bd-4ad8-808e-f5ce1bd22704"),
                            Name = "ALZPSPVSGXBZQHR",
                            Price = 4539
                        },
                        new
                        {
                            Id = 6,
                            Amount = 86,
                            Code = new Guid("16522253-8ddb-49bc-862e-f59fbabdd1f8"),
                            Name = "IZYNPHDEZTRHOJQ",
                            Price = 6449
                        },
                        new
                        {
                            Id = 7,
                            Amount = 25,
                            Code = new Guid("682b647b-68e8-4169-aa04-57290135e7c3"),
                            Name = "SNWLIRNVEHHBWHB",
                            Price = 4440
                        },
                        new
                        {
                            Id = 8,
                            Amount = 572,
                            Code = new Guid("2b92d841-2add-4b7d-bce9-f285162a27e7"),
                            Name = "FWARBGFDZPMZXYT",
                            Price = 4015
                        },
                        new
                        {
                            Id = 9,
                            Amount = 10,
                            Code = new Guid("92baf413-968b-49ca-a47d-2999cc6a12f1"),
                            Name = "ULGWPWZTFQKCVSG",
                            Price = 4080
                        },
                        new
                        {
                            Id = 10,
                            Amount = 539,
                            Code = new Guid("a23650b2-f0ef-4f62-83b9-50e89e9d7182"),
                            Name = "GTABXYVYRLLFQQU",
                            Price = 9094
                        },
                        new
                        {
                            Id = 11,
                            Amount = 851,
                            Code = new Guid("b9d9033b-d71c-452d-a753-d5df5d896187"),
                            Name = "HICYMJQRWVKIEWB",
                            Price = 4558
                        },
                        new
                        {
                            Id = 12,
                            Amount = 556,
                            Code = new Guid("029cd7e0-0829-425e-8c2f-9eac3e63cfe5"),
                            Name = "NTGQPMDEYFNPFKN",
                            Price = 2988
                        },
                        new
                        {
                            Id = 13,
                            Amount = 526,
                            Code = new Guid("05766146-7f78-47fe-97b5-477929e629a5"),
                            Name = "RKVVQBAQUAVDCIF",
                            Price = 1239
                        },
                        new
                        {
                            Id = 14,
                            Amount = 929,
                            Code = new Guid("c6bf6084-df6b-48cf-a2f6-9d6df92842bc"),
                            Name = "ABYXVSXUIWGDVJP",
                            Price = 8635
                        },
                        new
                        {
                            Id = 15,
                            Amount = 776,
                            Code = new Guid("a4bd4657-b9cd-412b-afe3-e49d4172997f"),
                            Name = "XWDELBZCVOCIVXP",
                            Price = 1297
                        },
                        new
                        {
                            Id = 16,
                            Amount = 369,
                            Code = new Guid("682c989f-da30-4129-bf94-eadd74fc55bb"),
                            Name = "RBHOJLZBWYZFLEF",
                            Price = 6185
                        },
                        new
                        {
                            Id = 17,
                            Amount = 909,
                            Code = new Guid("04f066be-8bc6-4946-9f7c-900b1e728f51"),
                            Name = "RVHWPBGLENPOZIJ",
                            Price = 1248
                        },
                        new
                        {
                            Id = 18,
                            Amount = 698,
                            Code = new Guid("26569654-d105-4af1-92b2-cb5394aa5f5d"),
                            Name = "FTSRJHAEBDNCIXP",
                            Price = 1773
                        },
                        new
                        {
                            Id = 19,
                            Amount = 911,
                            Code = new Guid("f2797e7b-29b9-449c-8b0e-af56c7c33735"),
                            Name = "WGNWXYLFONOHLLO",
                            Price = 1677
                        },
                        new
                        {
                            Id = 20,
                            Amount = 964,
                            Code = new Guid("6ffe78c1-2933-4dbd-b954-ceef8c6eddd5"),
                            Name = "HRRAAIRWJRKPSFJ",
                            Price = 5761
                        },
                        new
                        {
                            Id = 21,
                            Amount = 136,
                            Code = new Guid("eb0656fb-86a7-4e62-ba87-bf770805f011"),
                            Name = "YYDOYAAEGBPEVBA",
                            Price = 8866
                        },
                        new
                        {
                            Id = 22,
                            Amount = 735,
                            Code = new Guid("a25358bb-1a3b-47ba-b2a0-77030433931d"),
                            Name = "OUCQTCYJZGWWZEV",
                            Price = 8688
                        },
                        new
                        {
                            Id = 23,
                            Amount = 224,
                            Code = new Guid("f81941d3-662d-4f77-af9b-63e9f95bc415"),
                            Name = "AKBAGNICHJAVGPF",
                            Price = 6303
                        },
                        new
                        {
                            Id = 24,
                            Amount = 712,
                            Code = new Guid("1c9814f0-52fc-46c9-8e2e-b675ff863db6"),
                            Name = "YKAKBOZDNUHROMP",
                            Price = 3173
                        },
                        new
                        {
                            Id = 25,
                            Amount = 92,
                            Code = new Guid("83a1f76a-5f31-4448-972d-680badff3b2a"),
                            Name = "YINXOHXJZDQHRWC",
                            Price = 4624
                        },
                        new
                        {
                            Id = 26,
                            Amount = 681,
                            Code = new Guid("273d5247-e5c6-4c61-a89a-4c0936743724"),
                            Name = "QTTVDFQNTPWZTZD",
                            Price = 5979
                        },
                        new
                        {
                            Id = 27,
                            Amount = 535,
                            Code = new Guid("b9093027-d8d0-4d29-8f13-647ee812a88e"),
                            Name = "UFCEOSDXWTPRSFN",
                            Price = 2667
                        },
                        new
                        {
                            Id = 28,
                            Amount = 659,
                            Code = new Guid("2eb030c6-1162-4751-a96b-dcf4dcb38b82"),
                            Name = "JKQIKIKHFIBOYPJ",
                            Price = 7631
                        },
                        new
                        {
                            Id = 29,
                            Amount = 719,
                            Code = new Guid("94ebd854-54aa-426a-ad3d-8854f734ea2e"),
                            Name = "WOKZCVMPIFOLRCT",
                            Price = 4654
                        },
                        new
                        {
                            Id = 30,
                            Amount = 190,
                            Code = new Guid("604e2dff-c0a9-4975-90fc-8572dac08256"),
                            Name = "RNAFUJSMOAYPRBH",
                            Price = 1843
                        },
                        new
                        {
                            Id = 31,
                            Amount = 273,
                            Code = new Guid("05249b4b-b8ad-4b2c-818b-60dca90d15b9"),
                            Name = "QXLDLBNNUADAZIU",
                            Price = 6253
                        },
                        new
                        {
                            Id = 32,
                            Amount = 794,
                            Code = new Guid("7aaa253c-db00-417f-b471-de4c845b977f"),
                            Name = "TIBLJBWLLNLBYAG",
                            Price = 2381
                        },
                        new
                        {
                            Id = 33,
                            Amount = 521,
                            Code = new Guid("23125e74-5bda-4f5a-b23f-39c98dc93700"),
                            Name = "WXLKFAYMXGCZNPW",
                            Price = 6870
                        },
                        new
                        {
                            Id = 34,
                            Amount = 145,
                            Code = new Guid("6b12a150-717a-4c77-b3ea-62079854c786"),
                            Name = "ESYKOVVIXNZAFRB",
                            Price = 7869
                        },
                        new
                        {
                            Id = 35,
                            Amount = 390,
                            Code = new Guid("2a9fd601-a1e7-44fa-9d60-6e9beb512a53"),
                            Name = "YMUSOFKKQQXXZVB",
                            Price = 9485
                        },
                        new
                        {
                            Id = 36,
                            Amount = 491,
                            Code = new Guid("f1578748-bed7-46e3-a27e-6eaa461838ab"),
                            Name = "VKHGVHHPPPXRKFH",
                            Price = 7852
                        },
                        new
                        {
                            Id = 37,
                            Amount = 302,
                            Code = new Guid("f76941b1-ddcd-44cb-9739-c6db34a80242"),
                            Name = "PVFKDTZSUMKQPYQ",
                            Price = 5604
                        },
                        new
                        {
                            Id = 38,
                            Amount = 52,
                            Code = new Guid("04aa263a-3ad5-4179-a3e2-e58492a1da19"),
                            Name = "FMBOMASQCDPDMHC",
                            Price = 6131
                        },
                        new
                        {
                            Id = 39,
                            Amount = 619,
                            Code = new Guid("3351c822-3cf4-42a2-8da8-f6dbc116687b"),
                            Name = "NGBUXODEQETZZLI",
                            Price = 4525
                        },
                        new
                        {
                            Id = 40,
                            Amount = 749,
                            Code = new Guid("ce36e390-edeb-4d52-ac06-fe6152d91099"),
                            Name = "RKXUDLPJEUHURXJ",
                            Price = 8057
                        },
                        new
                        {
                            Id = 41,
                            Amount = 683,
                            Code = new Guid("0a7a8deb-f6f8-4ea0-b0c1-6a83ffeb5841"),
                            Name = "ZQXPJBTKNBHEUHU",
                            Price = 9300
                        },
                        new
                        {
                            Id = 42,
                            Amount = 225,
                            Code = new Guid("704277af-1fc6-43cf-bc55-03c61e69b900"),
                            Name = "MTUJKZTVWFMIPYZ",
                            Price = 8018
                        },
                        new
                        {
                            Id = 43,
                            Amount = 31,
                            Code = new Guid("fdd0bfba-9a78-4945-b131-f81b2f1519ba"),
                            Name = "PHWRNBWPBDLEHJH",
                            Price = 2495
                        },
                        new
                        {
                            Id = 44,
                            Amount = 278,
                            Code = new Guid("a776793d-83e4-4a67-9a98-4d9bf90713eb"),
                            Name = "RMGLOFPWKXTGGJV",
                            Price = 4052
                        },
                        new
                        {
                            Id = 45,
                            Amount = 715,
                            Code = new Guid("fe0663e0-3902-4085-baba-180981cf5321"),
                            Name = "TCRJENQOMQQBYTY",
                            Price = 6365
                        },
                        new
                        {
                            Id = 46,
                            Amount = 45,
                            Code = new Guid("664bed48-b556-42d1-850c-6de917a07343"),
                            Name = "IDCZXSROSHUGRFW",
                            Price = 1717
                        },
                        new
                        {
                            Id = 47,
                            Amount = 57,
                            Code = new Guid("7192eb81-55d8-4cea-9b3d-458acb2ebca1"),
                            Name = "QHKUOXSRJFNSPUK",
                            Price = 7503
                        },
                        new
                        {
                            Id = 48,
                            Amount = 781,
                            Code = new Guid("32c1c99c-0ec6-487a-bb74-070b5cf3e4c2"),
                            Name = "HOHIEMNPMZGIEWA",
                            Price = 5705
                        },
                        new
                        {
                            Id = 49,
                            Amount = 575,
                            Code = new Guid("51093578-ad68-40b0-b320-4b99f47caa5a"),
                            Name = "NTKUVQURIGNJLEC",
                            Price = 3628
                        },
                        new
                        {
                            Id = 50,
                            Amount = 121,
                            Code = new Guid("d4ba2f33-4387-48ac-80a4-6767b9d8d4db"),
                            Name = "IUNWOWCQZKGDGNB",
                            Price = 1513
                        },
                        new
                        {
                            Id = 51,
                            Amount = 584,
                            Code = new Guid("d7517e42-efd2-4553-95d7-4b246cc0df96"),
                            Name = "YFYFCEVZWHNOQHP",
                            Price = 1502
                        },
                        new
                        {
                            Id = 52,
                            Amount = 602,
                            Code = new Guid("ceb58f2a-7d20-4216-9a99-e92429a96a33"),
                            Name = "TCVVAQRSPPYXCOL",
                            Price = 3694
                        },
                        new
                        {
                            Id = 53,
                            Amount = 247,
                            Code = new Guid("5492b255-3f0f-459d-b637-9a63098b4d98"),
                            Name = "PVCAENMMNYMBKAE",
                            Price = 5528
                        },
                        new
                        {
                            Id = 54,
                            Amount = 816,
                            Code = new Guid("b800ea43-67c7-4625-a718-3571e9f95c44"),
                            Name = "BLIYZJXURETUFIA",
                            Price = 2144
                        },
                        new
                        {
                            Id = 55,
                            Amount = 896,
                            Code = new Guid("be4158f3-dc5f-4d83-b55f-dd82f1a544bb"),
                            Name = "MGXKGWFEFZUEFIU",
                            Price = 3128
                        },
                        new
                        {
                            Id = 56,
                            Amount = 49,
                            Code = new Guid("283efba6-3668-4a7d-8561-381341617feb"),
                            Name = "EVURBOPGQJOLODR",
                            Price = 3203
                        },
                        new
                        {
                            Id = 57,
                            Amount = 995,
                            Code = new Guid("1ef0fcf0-5363-4702-b55a-5007b0eb684f"),
                            Name = "LDLNGCEELWINJVQ",
                            Price = 5368
                        },
                        new
                        {
                            Id = 58,
                            Amount = 604,
                            Code = new Guid("a111b284-4a8f-4408-a6fb-10c4a7836592"),
                            Name = "SHAWEOZJVTLBLZJ",
                            Price = 8769
                        },
                        new
                        {
                            Id = 59,
                            Amount = 127,
                            Code = new Guid("987151bc-a9eb-48ff-a57c-132d3b488b49"),
                            Name = "TPTTSYWCJZNQEUY",
                            Price = 2351
                        },
                        new
                        {
                            Id = 60,
                            Amount = 708,
                            Code = new Guid("58350493-32b0-4f78-b46f-09e6eaa6de41"),
                            Name = "VNSCNKPGZGBRLOC",
                            Price = 6498
                        },
                        new
                        {
                            Id = 61,
                            Amount = 108,
                            Code = new Guid("3ccec910-9770-4c57-b6ee-433d5f9ac8fe"),
                            Name = "ZMUXASBTNOOTRYK",
                            Price = 4619
                        },
                        new
                        {
                            Id = 62,
                            Amount = 655,
                            Code = new Guid("ca66cc21-1a45-435b-85cb-2d139630cc1c"),
                            Name = "BWLEERZGJYUBZTD",
                            Price = 8421
                        },
                        new
                        {
                            Id = 63,
                            Amount = 130,
                            Code = new Guid("c3dd4e35-a3ec-4d43-aa59-5a3db1eab7af"),
                            Name = "BTWTTLIQSFCMLWK",
                            Price = 5324
                        },
                        new
                        {
                            Id = 64,
                            Amount = 747,
                            Code = new Guid("c07b1cbc-1d25-4e58-abbf-02555996336b"),
                            Name = "ZRLNBDRAYEDUEFA",
                            Price = 8954
                        },
                        new
                        {
                            Id = 65,
                            Amount = 705,
                            Code = new Guid("958fad03-d494-43d5-bc41-deb450199810"),
                            Name = "NPZHBPLBICXDNRA",
                            Price = 8918
                        },
                        new
                        {
                            Id = 66,
                            Amount = 876,
                            Code = new Guid("322d4d84-21c3-419f-bd05-0095c6afab68"),
                            Name = "XSDWFRCJBFSIZGS",
                            Price = 3072
                        },
                        new
                        {
                            Id = 67,
                            Amount = 880,
                            Code = new Guid("803e4b5e-b7fc-49b2-93fa-49a7b999d438"),
                            Name = "TDGDYRQHACTVLUY",
                            Price = 8538
                        },
                        new
                        {
                            Id = 68,
                            Amount = 332,
                            Code = new Guid("5d2acdcb-618a-4873-861b-758fb325d5b7"),
                            Name = "SOCRKMBCXJWOXJK",
                            Price = 1094
                        },
                        new
                        {
                            Id = 69,
                            Amount = 419,
                            Code = new Guid("bbd546ba-8fb8-4358-977f-5326f4f519ec"),
                            Name = "NZKDYZMRYFZRONE",
                            Price = 7715
                        },
                        new
                        {
                            Id = 70,
                            Amount = 185,
                            Code = new Guid("890125bd-7dbc-4631-87b0-5fe6ac51e848"),
                            Name = "RGQAELAFFXVZSAD",
                            Price = 1734
                        },
                        new
                        {
                            Id = 71,
                            Amount = 541,
                            Code = new Guid("79a463cd-2d2e-442e-973d-3274392097d3"),
                            Name = "OSRMQBXMUBNBPDS",
                            Price = 4822
                        },
                        new
                        {
                            Id = 72,
                            Amount = 845,
                            Code = new Guid("91a6eb69-e2b2-4d90-8573-9f43516bd132"),
                            Name = "ORBEMJGNFRTDVJL",
                            Price = 3335
                        },
                        new
                        {
                            Id = 73,
                            Amount = 698,
                            Code = new Guid("70fe364f-42b1-4f69-aa80-473abcf59003"),
                            Name = "XCJXGNGSTFPCBDC",
                            Price = 7032
                        },
                        new
                        {
                            Id = 74,
                            Amount = 57,
                            Code = new Guid("1fac1201-993f-489a-bc91-ccbdebecf12c"),
                            Name = "KGKIINBHANFLKUC",
                            Price = 9359
                        },
                        new
                        {
                            Id = 75,
                            Amount = 181,
                            Code = new Guid("533bbf24-3e9b-4949-8288-858680fbeaab"),
                            Name = "YSTJAVSIXAUFTLA",
                            Price = 5335
                        },
                        new
                        {
                            Id = 76,
                            Amount = 281,
                            Code = new Guid("de4baa94-195c-4dc3-adbe-f7b089107b66"),
                            Name = "CSYEZFKJJXWRYGZ",
                            Price = 6440
                        },
                        new
                        {
                            Id = 77,
                            Amount = 978,
                            Code = new Guid("3f6700f8-7dd6-417f-bbb9-6fd4ff50dcb8"),
                            Name = "QMZIWTJSWXFVYHK",
                            Price = 6472
                        },
                        new
                        {
                            Id = 78,
                            Amount = 988,
                            Code = new Guid("36c5202d-7158-4d03-8821-7c5fcbc491c1"),
                            Name = "MRTKACCZFIHXXEG",
                            Price = 6098
                        },
                        new
                        {
                            Id = 79,
                            Amount = 935,
                            Code = new Guid("ac0bf880-69bf-4e46-9cb8-454416e714ef"),
                            Name = "BTWEOSCQBKRRGWV",
                            Price = 7514
                        },
                        new
                        {
                            Id = 80,
                            Amount = 157,
                            Code = new Guid("7ae84757-bfd0-477d-ace1-afdbce440da9"),
                            Name = "QHCTPVRBNSWVZQC",
                            Price = 8846
                        },
                        new
                        {
                            Id = 81,
                            Amount = 803,
                            Code = new Guid("adee19da-875c-4102-b684-cf5df8f7c8a5"),
                            Name = "XVCXZTKDOZESGAC",
                            Price = 2281
                        },
                        new
                        {
                            Id = 82,
                            Amount = 589,
                            Code = new Guid("e84ea182-d09a-406c-8ed2-65c799959f8f"),
                            Name = "XBZONVNIZUAWZLU",
                            Price = 8099
                        },
                        new
                        {
                            Id = 83,
                            Amount = 710,
                            Code = new Guid("318e0aaa-1cdf-4ec7-ae4b-741755e9c050"),
                            Name = "KMWZIHULGENCLXV",
                            Price = 4192
                        },
                        new
                        {
                            Id = 84,
                            Amount = 58,
                            Code = new Guid("9ce31c69-d223-4131-9b5b-a76a3e4c79de"),
                            Name = "NCPZLJCRIQRJYRM",
                            Price = 9087
                        },
                        new
                        {
                            Id = 85,
                            Amount = 84,
                            Code = new Guid("deb95c9e-208e-4628-91d9-902ac2ed8f0d"),
                            Name = "MHEKNCYGBHKRVZC",
                            Price = 6246
                        },
                        new
                        {
                            Id = 86,
                            Amount = 412,
                            Code = new Guid("4934a96c-d5d1-4f46-a75f-84ca41394220"),
                            Name = "GDPAYVATOBZSUVI",
                            Price = 6670
                        },
                        new
                        {
                            Id = 87,
                            Amount = 255,
                            Code = new Guid("a46745c1-23a9-46f7-8270-cf578bf965c8"),
                            Name = "LHSUGPXWIOWZLOG",
                            Price = 3256
                        },
                        new
                        {
                            Id = 88,
                            Amount = 635,
                            Code = new Guid("79b48d65-5e93-4231-bbe6-4673ca1be34e"),
                            Name = "CBAJABZAYKCTFVE",
                            Price = 7118
                        },
                        new
                        {
                            Id = 89,
                            Amount = 129,
                            Code = new Guid("b6d1ef9c-be67-4bda-b2ca-e6367556eddc"),
                            Name = "JVEDACOOQEIGRKO",
                            Price = 3646
                        },
                        new
                        {
                            Id = 90,
                            Amount = 373,
                            Code = new Guid("04698d79-8b2f-4680-b648-ddc3a2ebbbb6"),
                            Name = "URBBVVGZAWFBGEB",
                            Price = 6063
                        },
                        new
                        {
                            Id = 91,
                            Amount = 73,
                            Code = new Guid("6d57c74c-989f-4523-b1c6-832221246569"),
                            Name = "QPEROVVJIJAPPHQ",
                            Price = 4213
                        },
                        new
                        {
                            Id = 92,
                            Amount = 34,
                            Code = new Guid("c7759fa5-71f2-4221-919e-aac8c468e66f"),
                            Name = "AKSHIBHKIBDICFL",
                            Price = 3584
                        },
                        new
                        {
                            Id = 93,
                            Amount = 200,
                            Code = new Guid("ab930912-8040-4fb1-800c-7583e2b8e3fe"),
                            Name = "DWMOSYJGBFAJUZF",
                            Price = 7771
                        },
                        new
                        {
                            Id = 94,
                            Amount = 510,
                            Code = new Guid("72313c05-ec72-40db-a7ea-aaff5e0b60cb"),
                            Name = "QXNMQMIFCERQHCJ",
                            Price = 8998
                        },
                        new
                        {
                            Id = 95,
                            Amount = 539,
                            Code = new Guid("8cb2cb5f-8234-4b3e-b0a2-8733c2d31171"),
                            Name = "RNERYJYHAHGFSTG",
                            Price = 4494
                        },
                        new
                        {
                            Id = 96,
                            Amount = 540,
                            Code = new Guid("415d73e7-8fb9-4a86-93fa-6649ef7081d0"),
                            Name = "BTIMOECICLZIFNU",
                            Price = 4945
                        },
                        new
                        {
                            Id = 97,
                            Amount = 854,
                            Code = new Guid("e77a5644-1103-441a-86e9-e4f937612641"),
                            Name = "LOUWDYBVJMEADKQ",
                            Price = 3648
                        },
                        new
                        {
                            Id = 98,
                            Amount = 874,
                            Code = new Guid("f83cc943-4203-4d3c-973c-abbdd2809b96"),
                            Name = "RIRDXHINLALVSOF",
                            Price = 1836
                        },
                        new
                        {
                            Id = 99,
                            Amount = 274,
                            Code = new Guid("b48d98d2-3b40-4631-ab70-7c2248120f25"),
                            Name = "PPGJUXYMUKJTWOD",
                            Price = 2119
                        },
                        new
                        {
                            Id = 100,
                            Amount = 870,
                            Code = new Guid("b3c969df-1528-48b4-ad1d-8c27dc88234c"),
                            Name = "OBANZXRXEHDWOOU",
                            Price = 6330
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
