// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORMShowdown;

#nullable disable

namespace ORMShowdown.Migrations
{
    [DbContext(typeof(EFCoreDbContext))]
    [Migration("20230624171820_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ORMShowdown.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product 1",
                            Price = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product 2",
                            Price = 20
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product 3",
                            Price = 30
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product 4",
                            Price = 40
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product 5",
                            Price = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
