// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORMShowdown;

#nullable disable

namespace ORMShowdown.Migrations
{
    [DbContext(typeof(EFCoreDbContext))]
    partial class EFCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ORMShowdown.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Random Product",
                            Price = 6357
                        },
                        new
                        {
                            Id = 2,
                            Name = "Random Product",
                            Price = 5245
                        },
                        new
                        {
                            Id = 3,
                            Name = "Random Product",
                            Price = 4264
                        },
                        new
                        {
                            Id = 4,
                            Name = "Random Product",
                            Price = 1921
                        },
                        new
                        {
                            Id = 5,
                            Name = "Random Product",
                            Price = 9498
                        },
                        new
                        {
                            Id = 6,
                            Name = "Random Product",
                            Price = 6780
                        },
                        new
                        {
                            Id = 7,
                            Name = "Random Product",
                            Price = 4173
                        },
                        new
                        {
                            Id = 8,
                            Name = "Random Product",
                            Price = 8781
                        },
                        new
                        {
                            Id = 9,
                            Name = "Random Product",
                            Price = 4231
                        },
                        new
                        {
                            Id = 10,
                            Name = "Random Product",
                            Price = 9098
                        },
                        new
                        {
                            Id = 11,
                            Name = "Random Product",
                            Price = 1206
                        },
                        new
                        {
                            Id = 12,
                            Name = "Random Product",
                            Price = 5072
                        },
                        new
                        {
                            Id = 13,
                            Name = "Random Product",
                            Price = 8168
                        },
                        new
                        {
                            Id = 14,
                            Name = "Random Product",
                            Price = 9064
                        },
                        new
                        {
                            Id = 15,
                            Name = "Random Product",
                            Price = 3587
                        },
                        new
                        {
                            Id = 16,
                            Name = "Random Product",
                            Price = 2027
                        },
                        new
                        {
                            Id = 17,
                            Name = "Random Product",
                            Price = 8302
                        },
                        new
                        {
                            Id = 18,
                            Name = "Random Product",
                            Price = 7690
                        },
                        new
                        {
                            Id = 19,
                            Name = "Random Product",
                            Price = 8641
                        },
                        new
                        {
                            Id = 20,
                            Name = "Random Product",
                            Price = 4552
                        },
                        new
                        {
                            Id = 21,
                            Name = "Random Product",
                            Price = 4906
                        },
                        new
                        {
                            Id = 22,
                            Name = "Random Product",
                            Price = 5782
                        },
                        new
                        {
                            Id = 23,
                            Name = "Random Product",
                            Price = 3820
                        },
                        new
                        {
                            Id = 24,
                            Name = "Random Product",
                            Price = 8285
                        },
                        new
                        {
                            Id = 25,
                            Name = "Random Product",
                            Price = 9818
                        },
                        new
                        {
                            Id = 26,
                            Name = "Random Product",
                            Price = 6889
                        },
                        new
                        {
                            Id = 27,
                            Name = "Random Product",
                            Price = 9005
                        },
                        new
                        {
                            Id = 28,
                            Name = "Random Product",
                            Price = 3309
                        },
                        new
                        {
                            Id = 29,
                            Name = "Random Product",
                            Price = 6733
                        },
                        new
                        {
                            Id = 30,
                            Name = "Random Product",
                            Price = 2058
                        },
                        new
                        {
                            Id = 31,
                            Name = "Random Product",
                            Price = 8491
                        },
                        new
                        {
                            Id = 32,
                            Name = "Random Product",
                            Price = 4529
                        },
                        new
                        {
                            Id = 33,
                            Name = "Random Product",
                            Price = 8212
                        },
                        new
                        {
                            Id = 34,
                            Name = "Random Product",
                            Price = 1301
                        },
                        new
                        {
                            Id = 35,
                            Name = "Random Product",
                            Price = 5946
                        },
                        new
                        {
                            Id = 36,
                            Name = "Random Product",
                            Price = 5115
                        },
                        new
                        {
                            Id = 37,
                            Name = "Random Product",
                            Price = 3697
                        },
                        new
                        {
                            Id = 38,
                            Name = "Random Product",
                            Price = 8275
                        },
                        new
                        {
                            Id = 39,
                            Name = "Random Product",
                            Price = 1185
                        },
                        new
                        {
                            Id = 40,
                            Name = "Random Product",
                            Price = 9276
                        },
                        new
                        {
                            Id = 41,
                            Name = "Random Product",
                            Price = 4513
                        },
                        new
                        {
                            Id = 42,
                            Name = "Random Product",
                            Price = 7661
                        },
                        new
                        {
                            Id = 43,
                            Name = "Random Product",
                            Price = 6700
                        },
                        new
                        {
                            Id = 44,
                            Name = "Random Product",
                            Price = 9753
                        },
                        new
                        {
                            Id = 45,
                            Name = "Random Product",
                            Price = 3591
                        },
                        new
                        {
                            Id = 46,
                            Name = "Random Product",
                            Price = 4216
                        },
                        new
                        {
                            Id = 47,
                            Name = "Random Product",
                            Price = 6697
                        },
                        new
                        {
                            Id = 48,
                            Name = "Random Product",
                            Price = 8343
                        },
                        new
                        {
                            Id = 49,
                            Name = "Random Product",
                            Price = 7045
                        },
                        new
                        {
                            Id = 50,
                            Name = "Random Product",
                            Price = 3492
                        },
                        new
                        {
                            Id = 51,
                            Name = "Random Product",
                            Price = 3852
                        },
                        new
                        {
                            Id = 52,
                            Name = "Random Product",
                            Price = 6699
                        },
                        new
                        {
                            Id = 53,
                            Name = "Random Product",
                            Price = 3791
                        },
                        new
                        {
                            Id = 54,
                            Name = "Random Product",
                            Price = 1332
                        },
                        new
                        {
                            Id = 55,
                            Name = "Random Product",
                            Price = 6622
                        },
                        new
                        {
                            Id = 56,
                            Name = "Random Product",
                            Price = 9791
                        },
                        new
                        {
                            Id = 57,
                            Name = "Random Product",
                            Price = 1984
                        },
                        new
                        {
                            Id = 58,
                            Name = "Random Product",
                            Price = 1784
                        },
                        new
                        {
                            Id = 59,
                            Name = "Random Product",
                            Price = 9931
                        },
                        new
                        {
                            Id = 60,
                            Name = "Random Product",
                            Price = 8684
                        },
                        new
                        {
                            Id = 61,
                            Name = "Random Product",
                            Price = 2465
                        },
                        new
                        {
                            Id = 62,
                            Name = "Random Product",
                            Price = 8337
                        },
                        new
                        {
                            Id = 63,
                            Name = "Random Product",
                            Price = 6599
                        },
                        new
                        {
                            Id = 64,
                            Name = "Random Product",
                            Price = 4808
                        },
                        new
                        {
                            Id = 65,
                            Name = "Random Product",
                            Price = 2887
                        },
                        new
                        {
                            Id = 66,
                            Name = "Random Product",
                            Price = 7752
                        },
                        new
                        {
                            Id = 67,
                            Name = "Random Product",
                            Price = 9405
                        },
                        new
                        {
                            Id = 68,
                            Name = "Random Product",
                            Price = 9814
                        },
                        new
                        {
                            Id = 69,
                            Name = "Random Product",
                            Price = 8306
                        },
                        new
                        {
                            Id = 70,
                            Name = "Random Product",
                            Price = 3576
                        },
                        new
                        {
                            Id = 71,
                            Name = "Random Product",
                            Price = 1418
                        },
                        new
                        {
                            Id = 72,
                            Name = "Random Product",
                            Price = 2082
                        },
                        new
                        {
                            Id = 73,
                            Name = "Random Product",
                            Price = 7517
                        },
                        new
                        {
                            Id = 74,
                            Name = "Random Product",
                            Price = 9106
                        },
                        new
                        {
                            Id = 75,
                            Name = "Random Product",
                            Price = 5644
                        },
                        new
                        {
                            Id = 76,
                            Name = "Random Product",
                            Price = 5208
                        },
                        new
                        {
                            Id = 77,
                            Name = "Random Product",
                            Price = 9667
                        },
                        new
                        {
                            Id = 78,
                            Name = "Random Product",
                            Price = 6227
                        },
                        new
                        {
                            Id = 79,
                            Name = "Random Product",
                            Price = 6562
                        },
                        new
                        {
                            Id = 80,
                            Name = "Random Product",
                            Price = 3230
                        },
                        new
                        {
                            Id = 81,
                            Name = "Random Product",
                            Price = 5585
                        },
                        new
                        {
                            Id = 82,
                            Name = "Random Product",
                            Price = 4369
                        },
                        new
                        {
                            Id = 83,
                            Name = "Random Product",
                            Price = 6697
                        },
                        new
                        {
                            Id = 84,
                            Name = "Random Product",
                            Price = 4084
                        },
                        new
                        {
                            Id = 85,
                            Name = "Random Product",
                            Price = 7618
                        },
                        new
                        {
                            Id = 86,
                            Name = "Random Product",
                            Price = 9333
                        },
                        new
                        {
                            Id = 87,
                            Name = "Random Product",
                            Price = 3793
                        },
                        new
                        {
                            Id = 88,
                            Name = "Random Product",
                            Price = 4216
                        },
                        new
                        {
                            Id = 89,
                            Name = "Random Product",
                            Price = 8451
                        },
                        new
                        {
                            Id = 90,
                            Name = "Random Product",
                            Price = 5842
                        },
                        new
                        {
                            Id = 91,
                            Name = "Random Product",
                            Price = 1781
                        },
                        new
                        {
                            Id = 92,
                            Name = "Random Product",
                            Price = 9593
                        },
                        new
                        {
                            Id = 93,
                            Name = "Random Product",
                            Price = 2551
                        },
                        new
                        {
                            Id = 94,
                            Name = "Random Product",
                            Price = 9967
                        },
                        new
                        {
                            Id = 95,
                            Name = "Random Product",
                            Price = 8030
                        },
                        new
                        {
                            Id = 96,
                            Name = "Random Product",
                            Price = 7021
                        },
                        new
                        {
                            Id = 97,
                            Name = "Random Product",
                            Price = 2149
                        },
                        new
                        {
                            Id = 98,
                            Name = "Random Product",
                            Price = 2184
                        },
                        new
                        {
                            Id = 99,
                            Name = "Random Product",
                            Price = 1291
                        },
                        new
                        { 
                            Id = 100, 
                            Name = "Random Product", 
                            Price = 2532 
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
